import { Chamber, User, Business, Post, Conversation } from './types';

// Sample chambers
export const chambers: Chamber[] = [
  {
    id: 'chamber_1',
    name: 'Novato Chamber of Commerce',
    location: 'Novato, CA',
    memberCount: 145,
    imageUrl: 'https://images.pexels.com/photos/2147161/pexels-photo-2147161.jpeg',
  },
  {
    id: 'chamber_2',
    name: 'Rohnert Park Chamber of Commerce',
    location: 'Rohnert Park, CA',
    memberCount: 98,
    imageUrl: 'https://images.pexels.com/photos/3285104/pexels-photo-3285104.jpeg',
  },
  {
    id: 'chamber_3',
    name: 'Windsor Chamber of Commerce',
    location: 'Windsor, CA',
    memberCount: 72,
    imageUrl: 'https://images.pexels.com/photos/2406731/pexels-photo-2406731.jpeg',
  },
];

// Sample users
export const users: User[] = [
  {
    id: 'user_1',
    username: 'johndoe',
    email: 'john@example.com',
    fullName: 'John Doe',
    title: 'Marketing Director',
    company: 'Acme Corp',
    bio: 'Marketing professional with 10+ years of experience in digital marketing strategies.',
    phone: '(555) 123-4567',
    linkedIn: 'linkedin.com/in/johndoe',
    memberSince: '2022-01-15',
    chamberId: 'chamber_1',
    imageUrl: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg',
  },
  {
    id: 'user_2',
    username: 'sarahjones',
    email: 'sarah@example.com',
    fullName: 'Sarah Jones',
    title: 'Business Development Manager',
    company: 'Innovate Inc',
    bio: 'Passionate about connecting businesses and creating growth opportunities.',
    phone: '(555) 987-6543',
    linkedIn: 'linkedin.com/in/sarahjones',
    memberSince: '2021-08-22',
    chamberId: 'chamber_1',
    imageUrl: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg',
  },
];

// Sample businesses
export const businesses: Business[] = [
  {
    id: 'business_1',
    name: 'TechSolutions Inc',
    category: 'Technology',
    description: 'IT services and solutions for small to medium businesses. Specializing in cloud migration, security, and managed services.',
    email: 'info@techsolutions.example',
    phone: '(555) 234-5678',
    website: 'techsolutions.example',
    address: '123 Tech Lane, Novato, CA 94945',
    chamberId: 'chamber_1',
    ownerId: 'user_1',
    services: ['Cloud Solutions', 'IT Support', 'Cybersecurity', 'Network Management'],
    imageUrl: 'https://images.pexels.com/photos/3183150/pexels-photo-3183150.jpeg',
  },
  {
    id: 'business_2',
    name: 'Green Leaf Landscaping',
    category: 'Services',
    description: 'Professional landscaping and garden design services for residential and commercial properties.',
    email: 'contact@greenleaf.example',
    phone: '(555) 876-5432',
    website: 'greenleaf.example',
    address: '456 Garden Way, Novato, CA 94947',
    chamberId: 'chamber_1',
    ownerId: 'user_2',
    services: ['Landscape Design', 'Garden Maintenance', 'Irrigation Systems', 'Hardscaping'],
    imageUrl: 'https://images.pexels.com/photos/589/garden-green-grass-trees.jpg',
  },
  {
    id: 'business_3',
    name: 'Coastal Accounting',
    category: 'Accounting',
    description: 'Full-service accounting firm providing bookkeeping, tax preparation, and financial planning for businesses.',
    email: 'info@coastalaccounting.example',
    phone: '(555) 456-7890',
    website: 'coastalaccounting.example',
    address: '789 Financial Blvd, Rohnert Park, CA 94928',
    chamberId: 'chamber_2',
    ownerId: null,
    services: ['Tax Preparation', 'Bookkeeping', 'Financial Planning', 'Payroll Services'],
    imageUrl: 'https://images.pexels.com/photos/53621/calculator-calculation-insurance-finance-53621.jpeg',
  },
  {
    id: 'business_4',
    name: 'Vineyard View Realty',
    category: 'Real Estate',
    description: 'Local real estate agency specializing in residential and commercial properties throughout Sonoma County.',
    email: 'sales@vineyardview.example',
    phone: '(555) 345-6789',
    website: 'vineyardview.example',
    address: '101 Realty Row, Windsor, CA 95492',
    chamberId: 'chamber_3',
    ownerId: null,
    services: ['Residential Sales', 'Commercial Properties', 'Property Management', 'Real Estate Consulting'],
    imageUrl: 'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg',
  },
  {
    id: 'business_5',
    name: 'Sonoma Brew House',
    category: 'Food & Beverage',
    description: 'Craft brewery and gastropub featuring locally sourced ingredients and seasonal menu items.',
    email: 'info@sonomabrew.example',
    phone: '(555) 789-0123',
    website: 'sonomabrew.example',
    address: '202 Brewery Lane, Rohnert Park, CA 94928',
    chamberId: 'chamber_2',
    ownerId: null,
    services: ['Craft Beers', 'Restaurant', 'Private Events', 'Catering'],
    imageUrl: 'https://images.pexels.com/photos/159291/beer-machine-alcohol-brewery-159291.jpeg',
  },
];

// Sample posts
export const posts: Post[] = [
  {
    id: 'post_1',
    title: 'Monthly Networking Breakfast',
    content: 'Join us for our monthly networking breakfast at the Novato Community Center. Great opportunity to meet fellow chamber members and build valuable connections.',
    type: 'event',
    date: '2023-07-01T08:00:00Z',
    author: {
      id: 'chamber_1',
      name: 'Novato Chamber of Commerce',
      imageUrl: 'https://images.pexels.com/photos/2147161/pexels-photo-2147161.jpeg',
    },
    commentCount: 5,
    chamberId: 'chamber_1',
    eventDetails: {
      date: 'July 15, 2023 at 8:00 AM',
      location: 'Novato Community Center, 901 Sherman Ave',
    },
  },
  {
    id: 'post_2',
    title: 'Looking for recommendations for commercial cleaning services',
    content: 'Our office building needs a reliable cleaning service for our 15,000 sq ft space. Preferably someone with experience in commercial properties and eco-friendly cleaning options. Any recommendations from fellow chamber members?',
    type: 'question',
    date: '2023-06-28T15:30:00Z',
    author: {
      id: 'user_1',
      name: 'John Doe',
      imageUrl: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg',
    },
    commentCount: 8,
    chamberId: 'chamber_1',
  },
  {
    id: 'post_3',
    title: 'TechSolutions Inc Celebrating 10 Years in Business!',
    content: "We're excited to announce that TechSolutions Inc is celebrating our 10th anniversary this month! To thank our community, we're offering free IT assessments to all chamber members throughout July. Contact us to schedule yours!",
    type: 'update',
    date: '2023-06-25T11:15:00Z',
    author: {
      id: 'business_1',
      name: 'TechSolutions Inc',
      imageUrl: 'https://images.pexels.com/photos/3183150/pexels-photo-3183150.jpeg',
    },
    commentCount: 12,
    chamberId: 'chamber_1',
  },
  {
    id: 'post_4',
    title: 'Summer Business Expo',
    content: 'The Rohnert Park Chamber of Commerce invites all businesses to participate in our annual Summer Business Expo. Showcase your products and services to the community and connect with potential customers.',
    type: 'event',
    date: '2023-06-20T09:45:00Z',
    author: {
      id: 'chamber_2',
      name: 'Rohnert Park Chamber of Commerce',
      imageUrl: 'https://images.pexels.com/photos/3285104/pexels-photo-3285104.jpeg',
    },
    commentCount: 3,
    chamberId: 'chamber_2',
    eventDetails: {
      date: 'August 5-6, 2023 from 10:00 AM to 4:00 PM',
      location: 'Rohnert Park Community Center, 5401 Snyder Lane',
    },
  },
  {
    id: 'post_5',
    title: 'Ribbon Cutting for New Downtown Office',
    content: 'Vineyard View Realty is proud to announce the opening of our new office in downtown Windsor! Join us for a ribbon cutting ceremony and open house. Refreshments will be served.',
    type: 'event',
    date: '2023-06-15T14:20:00Z',
    author: {
      id: 'business_4',
      name: 'Vineyard View Realty',
      imageUrl: 'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg',
    },
    commentCount: 7,
    chamberId: 'chamber_3',
    eventDetails: {
      date: 'July 22, 2023 at 3:00 PM',
      location: '305 Windsor River Road, Windsor, CA',
    },
  },
];

// Sample conversations
export const conversations: Conversation[] = [
  {
    id: 'conv_1',
    participant: {
      id: 'user_2',
      name: 'Sarah Jones',
      imageUrl: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg',
    },
    lastMessage: {
      id: 'msg_5',
      content: 'Looking forward to seeing you at the networking event tomorrow!',
      date: '2023-06-30T16:45:00Z',
      senderId: 'user_2',
      read: false,
    },
    messages: [
      {
        id: 'msg_1',
        content: "Hi John, I saw your company at the last chamber event. I'd love to discuss a potential collaboration.",
        date: '2023-06-29T10:15:00Z',
        senderId: 'user_2',
        read: true,
      },
      {
        id: 'msg_2',
        content: 'Hello Sarah, that sounds great! What kind of collaboration did you have in mind?',
        date: '2023-06-29T11:30:00Z',
        senderId: 'current_user',
        read: true,
      },
      {
        id: 'msg_3',
        content: "We're launching a new service next month and I think your tech expertise would be valuable. Do you have time for a coffee meeting?",
        date: '2023-06-29T14:20:00Z',
        senderId: 'user_2',
        read: true,
      },
      {
        id: 'msg_4',
        content: "Absolutely! I'm free most afternoons next week. How about Tuesday at 2pm?",
        date: '2023-06-30T09:10:00Z',
        senderId: 'current_user',
        read: true,
      },
      {
        id: 'msg_5',
        content: 'Looking forward to seeing you at the networking event tomorrow!',
        date: '2023-06-30T16:45:00Z',
        senderId: 'user_2',
        read: false,
      },
    ],
  },
  {
    id: 'conv_2',
    participant: {
      id: 'business_3',
      name: 'Coastal Accounting',
      imageUrl: 'https://images.pexels.com/photos/53621/calculator-calculation-insurance-finance-53621.jpeg',
    },
    lastMessage: {
      id: 'msg_8',
      content: "I've attached our service brochure for your review. Let me know if you have any questions!",
      date: '2023-06-28T13:25:00Z',
      senderId: 'business_3',
      read: true,
    },
    messages: [
      {
        id: 'msg_6',
        content: "Hello, I'm interested in your bookkeeping services for my small business. What packages do you offer?",
        date: '2023-06-28T11:05:00Z',
        senderId: 'current_user',
        read: true,
      },
      {
        id: 'msg_7',
        content: 'Hi there! Thanks for reaching out. We offer several tiers of bookkeeping services depending on your business needs and size.',
        date: '2023-06-28T11:35:00Z',
        senderId: 'business_3',
        read: true,
      },
      {
        id: 'msg_8',
        content: "I've attached our service brochure for your review. Let me know if you have any questions!",
        date: '2023-06-28T13:25:00Z',
        senderId: 'business_3',
        read: true,
      },
    ],
  },
];